package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/asolgan/lattice/cmd/lattice/output"
	"github.com/asolgan/lattice/internal/bootstrap"
	"github.com/asolgan/lattice/internal/processor"
	"github.com/asolgan/lattice/internal/substrate"
	loftspacedomain "github.com/asolgan/lattice/packages/loftspace-domain"
)

// leaseDocLinkName is the object-attachment slot the produced signed-lease
// artifact is linked under on the leaseapp. It is distinct from the manual
// document-upload slots (proofOfIncome / identityDoc / signedLeaseUpload) so the
// system-generated executed lease is its own well-known relation.
const leaseDocLinkName = "signedLease"

// leaseDocStoreNamespace seeds the deterministic object store name for a
// leaseapp's signed-lease artifact: derived from the leaseapp key alone, so a
// re-produce of the (deterministic) document overwrites the SAME store object
// rather than leaking an orphan blob on every call.
const leaseDocStoreNamespace = "loftspace:lease-doc:store:"

// handleLeaseDocument routes /api/lease-document — the produced executed-lease
// artifact for a signed application:
//
//	GET  /api/lease-document?leaseAppKey=  → stream the lease text for download
//	POST /api/lease-document {leaseAppKey} → durably attach the artifact, return oid
//
// The document is a deterministic function of the application's projected terms
// + the applicant's name (both lens read models, never Core KV — P5). The GET
// path regenerates and streams the same bytes the POST path attaches, so a
// download never waits on object-store projection lag; the POST path produces the
// durable, GC-protected artifact so both parties have the executed document on
// file (the on-SignLease "produce the signed lease" requirement).
//
// GET reads through the PROTECTED, RLS-scoped read_lease_applications model as
// an authenticated actor (D1.5 — buildLeaseDocumentForActor); POST still reads
// the unscoped weaver-targets convergence row via buildLeaseDocument, since it
// runs as the trusted system actor (s.adminActor) producing the canonical
// artifact on SignLease, not a user's read (D1 covers reads, not the internal
// service-actor write path).
func (s *server) handleLeaseDocument(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		s.handleLeaseDocumentGet(w, r)
	case http.MethodPost:
		s.handleLeaseDocumentAttach(w, r)
	default:
		s.writeError(w, http.StatusMethodNotAllowed,
			"expected GET /api/lease-document?leaseAppKey= or POST /api/lease-document {leaseAppKey}")
	}
}

// handleLeaseDocumentGet streams the executed-lease text for download, served
// as an AUTHENTICATED actor off the PROTECTED, RLS-scoped read_lease_applications
// model (D1.5 — the same read boundary handleApplications uses, D1.3 Fire 3): a
// missing/invalid bearer token is 401, and RLS scopes the document to the
// applicant themself — a leaseAppKey that isn't the caller's returns the same
// 404 as a genuinely absent one, so the caller cannot tell "not mine" from
// "not real."
func (s *server) handleLeaseDocumentGet(w http.ResponseWriter, r *http.Request) {
	actor, err := s.authenticateRead(r)
	if err != nil {
		s.writeError(w, http.StatusUnauthorized, "authentication required: "+err.Error())
		return
	}
	leaseAppKey := strings.TrimSpace(r.URL.Query().Get("leaseAppKey"))
	if leaseAppKey == "" {
		s.writeError(w, http.StatusBadRequest, "leaseAppKey query param is required")
		return
	}
	if s.pgPool == nil {
		s.writeError(w, http.StatusBadGateway,
			"protected read model not configured (set LOFTSPACE_APP_PG_DSN and ensure Postgres + the lease-signing protected lens are up)")
		return
	}

	ctx, cancel := s.reqContext(r)
	defer cancel()

	// s.conn (the applicant-name lookup) is nil-safe here: the RLS-scoped read and
	// the signed-document gate are the security/correctness boundary and need no
	// NATS read, so a down NATS connection degrades the document to the
	// applicant's bare key instead of failing the whole download (buildLeaseDocumentForActor).
	doc, status, msg := s.buildLeaseDocumentForActor(ctx, s.conn, actor.Subject, leaseAppKey)
	if doc == nil {
		s.writeError(w, status, msg)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Length", strconv.Itoa(len(doc.content)))
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Disposition", "attachment; filename=\""+doc.filename+"\"")
	w.Header().Set("Content-Security-Policy", "default-src 'none'; sandbox")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(doc.content)
}

// leaseAttachRequest is the POST body: the application whose executed lease to
// produce + attach.
type leaseAttachRequest struct {
	LeaseAppKey string `json:"leaseAppKey"`
}

// handleLeaseDocumentAttach produces the durable signed-lease artifact: it writes
// the generated bytes to the core-objects store under a deterministic, leaseapp-
// derived store name (a re-produce overwrites, never orphans) and submits
// AttachObject to link vtx.object.<oid> to the leaseapp under the `signedLease`
// slot. Bytes first, then graph (a failed op leaves only collectable bytes). The
// AttachObject read set is [leaseAppKey] only — the owner the FE already names —
// so the app never probes Core KV (P5). Idempotent: the same signed application
// yields byte-identical content → the same digest/oid, and the content-derived
// requestId collapses a re-submit on the Contract #4 tracker.
func (s *server) handleLeaseDocumentAttach(w http.ResponseWriter, r *http.Request) {
	conn, ok := s.requireConn(w)
	if !ok {
		return
	}
	if s.adminActor == "" {
		s.writeError(w, http.StatusBadGateway,
			"admin actor not loaded; a valid bootstrap file (BOOTSTRAP_JSON_PATH) is required to submit ops")
		return
	}
	var req leaseAttachRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.writeError(w, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return
	}
	leaseAppKey := strings.TrimSpace(req.LeaseAppKey)
	if leaseAppKey == "" {
		s.writeError(w, http.StatusBadRequest, "leaseAppKey is required")
		return
	}

	ctx, cancel := s.reqContext(r)
	defer cancel()

	doc, status, msg := s.buildLeaseDocument(ctx, conn, leaseAppKey)
	if doc == nil {
		s.writeError(w, status, msg)
		return
	}

	storeName := substrate.DeriveNanoID(leaseDocStoreNamespace, leaseAppKey)
	info, err := conn.ObjectPut(ctx, bootstrap.CoreObjectsBucket, storeName,
		strings.NewReader(string(doc.content)), s.uploadCap)
	if err != nil {
		s.writeError(w, http.StatusBadGateway, "store lease document bytes: "+err.Error())
		return
	}
	oid := substrate.SHA256NanoID("object:" + info.Digest)

	payload := map[string]any{
		"digest": info.Digest, "size": info.Size, "contentType": "text/plain; charset=utf-8",
		"storeName": storeName, "targetKey": leaseAppKey, "linkName": leaseDocLinkName,
		"filename": doc.filename,
	}
	requestID := substrate.DeriveNanoID(attachReqNamespace,
		strings.Join([]string{info.Digest, leaseAppKey, leaseDocLinkName}, "\x00"))
	env := &processor.OperationEnvelope{
		RequestID:     requestID,
		Lane:          processor.LaneDefault,
		OperationType: "AttachObject",
		Actor:         s.adminActor,
		SubmittedAt:   time.Now().UTC().Format(time.RFC3339),
		Class:         "object",
		Payload:       mustJSON(payload),
		ContextHint:   &processor.ContextHint{Reads: []string{leaseAppKey}},
	}
	reply, err := output.SubmitOp(ctx, conn, env)
	if err != nil {
		_ = conn.ObjectDelete(ctx, bootstrap.CoreObjectsBucket, storeName)
		s.writeError(w, http.StatusBadGateway, "submit AttachObject: "+err.Error())
		return
	}
	if reply.Status == processor.ReplyStatusRejected {
		// A collapsed re-submit returns the cached committed reply (not rejected), so
		// a rejection here is a genuine fault (e.g. the leaseapp was tombstoned). The
		// bytes we just wrote have no vtx.object to anchor them — reclaim them so they
		// are not left as an un-GC-able orphan in the store (the upload-handler pattern).
		_ = conn.ObjectDelete(ctx, bootstrap.CoreObjectsBucket, storeName)
		s.writeJSON(w, http.StatusBadRequest, reply)
		return
	}
	s.writeJSON(w, http.StatusOK, map[string]any{
		"oid": oid, "linkName": leaseDocLinkName, "targetKey": leaseAppKey,
		"size": info.Size, "filename": doc.filename,
	})
}

// leaseDocument is a built executed-lease artifact: the rendered bytes plus the
// download filename.
type leaseDocument struct {
	content  []byte
	filename string
}

// buildLeaseDocument reads the application's projected convergence row and the
// applicant's name (both lens read models — P5) and renders the deterministic
// executed-lease text. It returns (nil, status, msg) when the application is
// absent or not yet signed — an executed lease cannot be produced for an
// unsigned application. The rendered bytes are a pure function of the projected
// fields (no clock read), so repeated builds are byte-identical.
func (s *server) buildLeaseDocument(ctx context.Context, conn *substrate.Conn, leaseAppKey string) (*leaseDocument, int, string) {
	row, ok := s.lookupApplication(ctx, conn, leaseAppKey)
	if !ok {
		return nil, http.StatusNotFound,
			"no application "+shortKeyServer(leaseAppKey)+" in the read model (is lease-signing installed and projecting?)"
	}
	applicantName := s.lookupApplicantName(ctx, conn, row.Applicant)
	return assembleLeaseDocument(row, applicantName)
}

// buildLeaseDocumentForActor is buildLeaseDocument's authenticated counterpart
// (D1.5): it reads the application through the PROTECTED, RLS-scoped
// read_lease_applications model as actorID rather than the unscoped
// weaver-targets bucket, so a leaseAppKey RLS does not grant the actor comes
// back not-found — identical to a genuinely absent key. conn is nil-safe: it
// resolves only the applicant's display name (a public roster projection, no
// authz anchor), so a nil conn (NATS unavailable) degrades the rendered
// document to the applicant's bare key rather than failing the request —
// the RLS-scoped fetch above is the actual security/correctness boundary.
func (s *server) buildLeaseDocumentForActor(ctx context.Context, conn *substrate.Conn, actorID, leaseAppKey string) (*leaseDocument, int, string) {
	protRow, ok, err := queryApplicationByKey(ctx, s.pgPool, actorID, leaseAppKey)
	if err != nil {
		s.logger.Error("read protected lease application for document", "error", err)
		return nil, http.StatusBadGateway, "could not read the protected lease-applications model"
	}
	if !ok {
		return nil, http.StatusNotFound,
			"no application "+shortKeyServer(leaseAppKey)+" in the read model (is lease-signing installed and projecting, and are you the applicant?)"
	}
	row := protectedRowToDocumentRow(protRow)
	var applicantName string
	if conn != nil {
		applicantName = s.lookupApplicantName(ctx, conn, row.Applicant)
	}
	return assembleLeaseDocument(row, applicantName)
}

// protectedRowToDocumentRow adapts the PROTECTED read model's row into the
// applicationRow shape assembleLeaseDocument/renderLeaseDocument render. The
// protected model carries no Weaver gap booleans (§10.2 stays Weaver-only), so
// MissingSignature is derived from an absent signed_at instead; absent optional
// columns stay nil/empty, the same degrade renderLeaseDocument already applies
// to a projection missing optional terms.
func protectedRowToDocumentRow(row protectedApplicationRow) applicationRow {
	out := applicationRow{
		EntityKey:          row.EntityKey,
		Applicant:          row.Applicant,
		UnitRent:           row.UnitRent,
		UnitBedrooms:       row.UnitBedrooms,
		UnitBathrooms:      row.UnitBathrooms,
		TermsLeaseTerm:     row.TermsLeaseTerm,
		TermsRequestedRent: row.TermsRequestedRent,
		UnitKey:            strDeref(row.UnitKey),
		UnitAddress:        strDeref(row.UnitAddress),
		UnitCity:           strDeref(row.UnitCity),
		UnitRegion:         strDeref(row.UnitRegion),
		UnitCurrency:       strDeref(row.UnitCurrency),
		UnitStatus:         strDeref(row.UnitStatus),
		UnitAvailableFrom:  strDeref(row.UnitAvailableFrom),
		SignedAt:           strDeref(row.SignedAt),
		TermsMoveInDate:    strDeref(row.TermsMoveInDate),
	}
	out.MissingSignature = out.SignedAt == ""
	return out
}

// strDeref returns "" for a nil pointer, the pointed-to value otherwise.
func strDeref(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// assembleLeaseDocument is the pure build step: it gates on the signature and
// renders the deterministic executed-lease text. It returns (nil, status, msg) for
// an unsigned application — an executed lease cannot be produced before signing.
func assembleLeaseDocument(row applicationRow, applicantName string) (*leaseDocument, int, string) {
	if row.MissingSignature || strings.TrimSpace(row.SignedAt) == "" {
		return nil, http.StatusConflict,
			"this application is not signed yet — sign the lease before producing the executed document"
	}
	content := renderLeaseDocument(row, applicantName)
	filename := "signed-lease-" + shortKeyServer(row.EntityKey) + ".txt"
	return &leaseDocument{content: []byte(content), filename: filename}, http.StatusOK, ""
}

// lookupApplication finds one leaseApplicationComplete row by its entityKey in the
// shared weaver-targets read model (P5). It reuses computeApplications' decode
// path (applicant="" lists all) and selects the matching anchor.
func (s *server) lookupApplication(ctx context.Context, conn *substrate.Conn, leaseAppKey string) (applicationRow, bool) {
	bucket := bootstrap.WeaverTargetsBucket
	keys, err := conn.KVListKeys(ctx, bucket)
	if err != nil {
		return applicationRow{}, false
	}
	get := func(key string) ([]byte, bool) {
		entry, err := conn.KVGet(ctx, bucket, key)
		if err != nil {
			return nil, false
		}
		return entry.Value, true
	}
	for _, row := range computeApplications(keys, get, "") {
		if row.EntityKey == leaseAppKey {
			return row, true
		}
	}
	return applicationRow{}, false
}

// lookupApplicantName resolves an applicant identity key to its human name via the
// applicantRoster read model (P5). An unresolved key (no roster row) degrades to
// the empty string — renderLeaseDocument falls back to the key so the document is
// still well-formed.
func (s *server) lookupApplicantName(ctx context.Context, conn *substrate.Conn, applicantKey string) string {
	if strings.TrimSpace(applicantKey) == "" {
		return ""
	}
	bucket := loftspacedomain.LoftspaceIdentitiesBucket
	keys, err := conn.KVListKeys(ctx, bucket)
	if err != nil {
		return ""
	}
	get := func(key string) ([]byte, bool) {
		entry, err := conn.KVGet(ctx, bucket, key)
		if err != nil {
			return nil, false
		}
		return entry.Value, true
	}
	for _, id := range computeIdentities(keys, get) {
		if id.Key == applicantKey {
			return id.Name
		}
	}
	return ""
}

// renderLeaseDocument renders the executed-lease text from a signed application's
// projected row and the applicant's name. It is deterministic — every line is
// drawn from the projected fields, with no clock read — so the same signed
// application always renders byte-identical bytes (the basis for the idempotent,
// orphan-free attach). Only present fields are emitted, so an application missing
// optional terms (no .terms, an older projection) degrades to whatever it carries
// rather than printing blanks.
func renderLeaseDocument(row applicationRow, applicantName string) string {
	var b strings.Builder
	line := func(label, value string) {
		if strings.TrimSpace(value) == "" {
			return
		}
		fmt.Fprintf(&b, "%-16s%s\n", label+":", value)
	}

	b.WriteString("RESIDENTIAL LEASE AGREEMENT\n")
	b.WriteString("===========================\n\n")
	b.WriteString("Executed electronically through LoftSpace.\n\n")

	b.WriteString("PARTIES & PREMISES\n")
	b.WriteString("------------------\n")
	tenant := applicantName
	if tenant == "" {
		tenant = row.Applicant
	}
	line("Tenant", tenant)
	if applicantName != "" && row.Applicant != "" {
		line("Tenant ID", row.Applicant)
	}
	line("Landlord", "LoftSpace property management")
	fullAddr := joinNonEmpty(", ", row.UnitAddress, row.UnitCity, row.UnitRegion)
	line("Premises", fullAddr)
	line("Unit", row.UnitKey)

	b.WriteString("\nLEASE TERMS\n")
	b.WriteString("-----------\n")
	line("Monthly rent", renderRent(row))
	if term := leaseTermMonths(row); term != "" {
		line("Lease term", term+" months")
	}
	if moveIn := firstNonEmpty(row.TermsMoveInDate, row.UnitAvailableFrom); moveIn != "" {
		line("Move-in date", moveIn)
	}
	if row.UnitBedrooms != nil {
		line("Bedrooms", trimFloat(*row.UnitBedrooms))
	}
	if row.UnitBathrooms != nil {
		line("Bathrooms", trimFloat(*row.UnitBathrooms))
	}

	b.WriteString("\nEXECUTION\n")
	b.WriteString("---------\n")
	line("Signed by", tenant)
	line("Signed on", row.SignedAt)
	line("Application", row.EntityKey)

	b.WriteString("\nThis document is a system-generated summary of the executed lease\n")
	b.WriteString("application and is provided for the records of both parties.\n")
	return b.String()
}

// renderRent formats the monthly rent with its currency: the bare-dollar form for
// USD / unspecified, "<amount> <CUR>" otherwise. The applicant's requested rent is
// noted when it differs from the listing ask.
func renderRent(row applicationRow) string {
	if row.UnitRent == nil {
		if row.TermsRequestedRent != nil {
			return trimFloat(*row.TermsRequestedRent) + " (applicant offer)"
		}
		return ""
	}
	cur := strings.TrimSpace(row.UnitCurrency)
	base := "$" + trimFloat(*row.UnitRent)
	if cur != "" && cur != "USD" {
		base = trimFloat(*row.UnitRent) + " " + cur
	}
	if row.TermsRequestedRent != nil && *row.TermsRequestedRent != *row.UnitRent {
		base += " (applicant offered " + trimFloat(*row.TermsRequestedRent) + ")"
	}
	return base
}

// leaseTermMonths picks the applicant's requested term, falling back to the
// listing's term.
func leaseTermMonths(row applicationRow) string {
	if row.TermsLeaseTerm != nil {
		return trimFloat(*row.TermsLeaseTerm)
	}
	if row.UnitLeaseTerm != nil {
		return trimFloat(*row.UnitLeaseTerm)
	}
	return ""
}

// trimFloat renders a projected numeric field without a trailing ".0" for whole
// numbers (12 not 12.0) while preserving any genuine fraction.
func trimFloat(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

// firstNonEmpty returns the first non-blank string.
func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

// joinNonEmpty joins the non-blank parts with sep.
func joinNonEmpty(sep string, parts ...string) string {
	kept := make([]string, 0, len(parts))
	for _, p := range parts {
		if strings.TrimSpace(p) != "" {
			kept = append(kept, p)
		}
	}
	return strings.Join(kept, sep)
}

// shortKeyServer abbreviates a vtx.<type>.<id> key to <type>.<id-prefix> for
// human-facing filenames / messages, mirroring the FE's shortKey.
func shortKeyServer(key string) string {
	parts := strings.Split(key, ".")
	if len(parts) >= 3 {
		id := parts[2]
		if len(id) > 8 {
			id = id[:8]
		}
		return parts[1] + "." + id
	}
	return key
}
